### PR TITLE
Avoid hardcoded BSONDocument

### PR DESCRIPTION
**Pull request by havocp**
This works, but there's a lot of stuff that could be done differently.
I just took a crack at it.

### CODE REVIEW

**Comment by bwmcadams** [comment]
Just FYI - I'm going to get to this in a bit.  It sounds like you're tackling the next functionality ring I had on my list to some degree and I want to make sure I digest this fully.

If you get a chance, FYI, I've been maintaining a Freenode IRC channel ##mongodb_scala (yes, that's two # marks) for discussions of stuff like this and it may be good to start coordinating contributors.

**Comment by bwmcadams** [comment]
I see the gist of what you're trying to do, and most of it makes sense.

But why expose the Result Type explicitly as a Parameter in
SingleDocQueryRequestFuture?  I've been finding it's actually cleaner API
wise and less prone to type erasure problems to use abstract types wherever
possible instead of Parameterized Types.

I would prefer to avoid them when I can.

Do you have a particular reason for using Parameterized types here that I'm
missing, that we can't accomplish with Abstract types?

**Comment by havocp** [comment]
Hi,

On Wed, Jul 6, 2011 at 1:40 PM, bwmcadams
reply@reply.github.com
wrote:

> Do you have a particular reason for using Parameterized types here that I'm
> missing, that we can't accomplish with Abstract types?

Thinking out loud on it,

The actual bug being solved was the three type errors present after
that change, where the type should have been the Result
(SerializableBSONDocument) but plain Document was used instead.

So my goal here was to get the compiler to flag those errors at
compile time, instead of barfing at runtime.

So say you have:

  def findOne[Qry <: BSONDocument, Flds <: BSONDocument,
Result](query: Qry = Document.empty, fields: Flds =
Document.empty)(callback:
SingleDocQueryRequestFuture[Result])(implicit concern: WriteConcern =
this.writeConcern, serializable : SerializableBSONObject[Result])

With abstract types, the question is how you constrain the type of
"callback" to allow only a SingleDocQueryRequestFuture that matches
Result and the SerializableBSONObject.

I guess you would have to write a structural type like

  (callback: SingleDocQueryRequestFuture { type V = Result })

(not sure if that compiles, but I'm pretty sure you can do something like that)

I guess RequestFutures.query() could also return that type, not sure:

  def query[A](...): SingleDocQueryRequestFuture { type V = A }

This would achieve the same goal I guess? I would have to try it to see.

I think one difference between the "V" in RequestFuture[V] and the T
is that "V" is part of the interface (what does the API user get from
the future?) while the T is sort of an implementation detail (how does
the future-provider complete the future). In most places that take a
future, only futures with the right V are OK, but any T would be fine
in principle as long as it gets mapped to V somehow.
V is "value type" and T is like "completion type". So T makes sense to
come from the subclass while V makes sense to be in the API. Well,
that's a theory anyway.

It's also possible to only do my last patch (the fix for the three
type errors) and not add the compile-time checks at all, i.e. just
leave the futures stuff alone. Really "catch this stuff at compile
time" and "fix the stuff" are pretty orthogonal.

Havoc

**Comment by bwmcadams** [comment]
I have to digest this a bit.

It is possible to access the abstract type however and do checks against
THAT, which may be what is needed.

I like how clean the API is right now w/o the parameters, and introducing
Manifests etc worries me a bit this early in.  But at the same time, we do
need strong compile time checks.

I'm in the middle of a BIG debug session of related code, writing my first
major external custom type serializer/deserializer.  Once that's done I'll
see how to graft this in to that code in a way that makes sense.  If I can
avoid the parameters I will but I agree with your sentiment that compile
safety is good.

**Comment by havocp** [comment]
You might want to flip the order of dealing with this from my three commits; first put in something like the last commit without the changes to find() insert() etc, just with the additions to SerializableBSONObject and code to use those additions. i.e. just fix the three type errors. And then you could get your external serializer/deserializer to work. You won't be able to make it work without those fixes I don't think - at least I couldn't. Then in a more leisurely way think about whether the compiler could catch this kind of bug.

**Comment by bwmcadams** [comment]
I've manually merged a start of this into havocp-wip-bsondoc-purge branch, for further exploration

**Comment by bwmcadams** [comment]
My current thought is that commands are too changeable  and slightly unknowable in their structure, and should be expected to return as BSON Documents on the main "command" interface.

runCommand is exposed (as used in findAndModify) for those who want to override the deserialization.

I am investigating the type safety questions --- I think I can ensure that w/ the abstract types.

**Pull request closed without merging**
